# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
revisionHistoryLimit: 1
image:
  repository: registry.ng.bluemix.net/replace-me-namespace/k8slisting
  tag: v1.0.0
  pullPolicy: Always
  resources:
    requests:
      cpu: 200m
      memory: 300Mi
livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
service:
  name: node
  type: NodePort
  servicePort: 3000
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  metrics:
    cpu:
      targetAverageUtilization: 70
    memory:
      targetAverageUtilization: 70
base:
  enabled: false
  replicaCount: 1
  image:
    tag : v0.9.9
  weight: 100
istio:
  enabled: false
  weight: 100
generatedBindings:
  enabled: true

envOfSecrets:
  envMONGOUSERNAME:
    name: MONGOUSERNAME
    secretKeyRef:
      name: mysecret
      key: MONGOUSERNAME
  envMONGOPASSWORD:
    name: MONGOPASSWORD
    secretKeyRef:
      name: mysecret
      key: MONGOPASSWORD

envOfConfigmaps:
  envMONGOPORT:
    name: MONGOPORT
    configMapKeyRef:
      name: env-database
      key: MONGOPORT
  envHOSTNAMEMONGODB:
    name: HOSTNAMEMONGODB
    configMapKeyRef:
      name: env-database
      key: HOSTNAMEMONGODB